var bankName;
console.log(bankName);
bankName ="SBI Bank";
console.log(typeof bankName);
console.log(bankName);
console.log("--------------------------------------------------");
var marks='90%';
console.log(marks);
console.log(typeof marks);
console.log("---------------------------------------------------");
var isWorking;
console.log(isWorking);
isWorking ="true";
console.log(typeof true);
console.log("---------------------------------------------------");
var totalCount="Hundred and Seven";
console.log(totalCount);
console.log(typeof totalCount);
var totalCount=107;
console.log(totalCount);
console.log(typeof totalCount);

